config/routes.rb
Rails.application.routes.draw do
  # Authentication routes
  devise_for :users

  # Application routes
  resources :houses, only: [:index, :create, :edit, :update, :destroy] do
    resources :invites, only: [:create]
  end
  resources :rooms, only: [:create, :edit, :update, :destroy]
  resources :boxes, only: [:show, :create, :destroy]
  resources :items do
    resources :tags, only: [] do
      delete :remove, on: :member
    end
  end
  resources :tags, only: [:index, :edit, :create, :update, :destroy]
  resources :invites, only: [:update]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "items#index"
end

app/models/box.rb
# frozen_string_literal: true

#  Represents any type of box that items can be stored in
class Box < ApplicationRecord
  belongs_to :house
  belongs_to :room, counter_cache: true
  has_many :items, dependent: :nullify

  before_validation :set_number, on: :create
  validates :number, presence: true, numericality: { only_integer: true }
  validates :number, uniqueness: { scope: :house_id }

  private

  def set_number
    highest_number_in_house = house&.boxes&.maximum(:number) || 0
    self.number ||= highest_number_in_house + 1
  end
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  before_action :set_box, only: %i[ show update destroy ]

  def index
    @boxes = policy_scope(Box)
  end

  def show
  end

  def create
    @box = Box.new(box_params)
    authorize @box

    if @box.save
      redirect_to new_item_path, notice: "Box was successfully created."
    else
      render "items/new", status: :unprocessable_entity
    end
  end

  def update
    if @box.update(box_params)
      redirect_to @box, notice: "Box was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @box.destroy!
    redirect_to boxes_url, notice: "Box was successfully destroyed.", status: :see_other
  end

  private

  def set_box
    @box = Box.find(params[:id])
  end

  def box_params
    params.require(:box).permit(:room_id)
  end
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/views/boxes/_box.html.erb
  <%= link_to box_path(box), class: "border-1 border-slate-200 bg-slate-950 rounded-xl shadow-md dark:shadow-md/90 p-4 max-w-2xl flex gap-2 hover:shadow-lg dark:shadow-lg/90 hover:-translate-y-1 transition ease-linear duration-150 active:translate-0 active:shadow-sm dark:active:shadow-sm/90" do %>
    <div class="flex flex-col gap-4">
      <div class="flex items-center gap-2">
        <%= render "shared/icons/box", klasses: "mt-1 max-h-min dark:stroke-slate-50" %>
        <h3 class="text-2xl col-span-2 text-slate-900 dark:text-slate-100">
          Box <%= box.number %>
        </h3>
      </div>

      <div class="text-lg flex flex-col gap-2 text-slate-700 stroke-slate-700 dark:text-slate-400 dark:stroke-slate-400">
        <div class="flex gap-2 items-center flex-wrap">
          <%= render "shared/icons/house" %>
          <%= box.house.name.capitalize %>
        </div>

        <div class="flex gap-2 items-center flex-wrap">
          <%= render "shared/icons/room" %>
          <%= box.room.name.capitalize %>
        </div>

        <div class="flex gap-2 items-center flex-wrap">
          <%= render "shared/icons/items" %>
          <%= box.items.count %> items
        </div>
      </div>
    </div>
<% end %>

app/views/boxes/_form.html.erb
<%= simple_form_for(box, html: { class: "p-2 rounded-xl bg-slate-100 dark:bg-slate-900 shadow-sm dark:shadow-sm/70 border-1 border-slate-200 dark:border-slate-800" }) do |f| %>
  <% if box.errors.any? %>
    <%= render "shared/form_errors", resource: box %>
  <% end %>
  <div class="flex gap-2">
    <%= f.input :room_id, as: :select,
      label: false,
      include_blank: "Room name",
      collection: rooms.map { |room| ["#{room.name.capitalize} - #{room.house.name.capitalize}", room.id] },
      error_html: { class: "text-red-400 text-sm mt-1" },
      wrapper_html: { class: "grow" },
      input_html: { class: "w-full rounded-md p-3 bg-slate-200 dark:bg-slate-800 focus:outline-none focus:ring-2 focus:ring-teal-400 text-slate-900 dark:text-slate-50" }
    %>
    <%= f.button :submit, "Add box", class: "cursor-pointer bg-teal-500 hover:bg-teal-600 text-slate-100 px-4 py-2 rounded shadow-sm focus:outline-none focus:ring-2 focus:ring-teal-400" %>
  </div>
<% end %>