config/routes.rb
Rails.application.routes.draw do
  # Authentication routes
  devise_for :users

  # Application routes
  resources :houses, only: [:index, :create, :edit, :update, :destroy] do
    resources :invites, only: [:create]
  end
  resources :rooms, only: [:create, :edit, :update, :destroy]
  resources :boxes, only: [:show, :create, :destroy]
  resources :items do
    resources :tags, only: [] do
      delete :remove, on: :member
    end
  end
  resources :tags, only: [:index, :edit, :create, :update, :destroy]
  resources :invites, only: [:update]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "items#index"
end

app/models/tag.rb
# frozen_string_literal: true

# A label on an item
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :items, through: :taggings

  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: %i[ update destroy remove ]
  before_action :set_item, only: %i[ remove ]

  def index
    @tags = policy_scope(Tag)
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    @tag.user = current_user
    authorize @tag

    if @tag.save
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.append(
            "tags_list",
            partial: "tags/tag",
            locals: { tag: @tag }
          )
        end
      end
    else
      render :index, status: :unprocessable_entity
    end
  end

  def update
    authorize @tag

    if @tag.update(tag_params)
      redirect_to @tag, notice: "Tag was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @tag
    @tag.destroy

    redirect_to tags_path, notice: "Tag deleted"
  end

  def remove
    authorize @tag
    @item.tags.delete(@tag)

    respond_to do |format|
      format.html { redirect_to items_path, notice: "Tag successfully removed from #{@item.name}." }
      format.turbo_stream do
        partial = params[:closed] == "true" ? "items/item" : "items/item_open"
        render turbo_stream: turbo_stream.replace(
          dom_id(@item),
          partial: partial,
          locals: { item: @item }
        )
      end
    end
  end

  private

  def set_item

    @item = Item.find(params[:item_id])
  end

  def set_tag
    @tag = Tag.find(params[:id])
  end

  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= turbo_frame_tag "title_#{dom_id(tag)}" do %>
  <%= simple_form_for(tag, html: { data: { turbo_frame: "title_#{dom_id(tag)}" }, class: "p-2 rounded-xl bg-slate-100 dark:bg-slate-900 shadow-sm dark:shadow-sm/70 border-1 border-slate-200 dark:border-slate-800"  }) do |f| %>

    <% if tag.errors.any? %>
      <%= render "shared/form_errors", resource: tag %>
    <% end %>

    <div class="flex gap-2">
      <%= f.input :name,
        label: "Tag name",
        label_html: { class: "sr-only" },
        placeholder: "Tag name",
        wrapper_html: { class: "grow" },
        error_html: { class: "text-red-400 text-sm mt-1" },
        input_html: {
          class: "grow w-full rounded-md bg-slate-200 dark:bg-slate-800 text-lg text-slate-950 dark:text-slate-100 placeholder:text-slate-500 placeholder:dark:text-slate-500 p-2 focus:outline-none focus:ring-2 focus:ring-teal-400"
        }
      %>

      <% if tag.id == nil %>
        <%= f.button :submit, "Add tag", class: "cursor-pointer bg-teal-500 hover:bg-teal-600 text-slate-100 px-4 py-2 rounded shadow-sm focus:outline-none focus:ring-2 focus:ring-teal-400" %>
      <% else %>
        <%= f.button :submit, "Save", class: "cursor-pointer bg-teal-500 hover:bg-teal-600 text-slate-100 px-4 py-2 rounded shadow-sm focus:outline-none focus:ring-2 focus:ring-teal-400" %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/tags/_tag.html.erb
<% item ||= nil %>
<% tag ||= nil %>

<div class="p-1 px-2 bg-slate-200 dark:bg-slate-400 rounded-xl inline-flex gap-1 justify-center items-center">
  <%= tag&.name %>
  <% if item.present? %>
    <%= link_to remove_item_tag_path(item, tag), data: { turbo_method: :delete }, class: "focus:outline-none focus:ring-2 focus:ring-teal-400" do %>
      <%= render "shared/icons/close_circle" %>
    <% end %>
  <% else %>
    <%= link_to tag_path(tag), data: { turbo_method: :delete }, class: "focus:outline-none focus:ring-2 focus:ring-teal-400" do %>
      <%= render "shared/icons/close_circle" %>
    <% end %>
  <% end %>
</div>

app/views/tags/index.html.erb
<h1 class="mt-8 mx-6 mb-4 text-4xl font-bold">
  Tags
</h1>

<div class="mx-2 mb-4">
  <%= render "tags/form", tag: @tag %>
</div>

<ul class="px-2 py-4 bg-slate-100 dark:bg-slate-900">
  <%= turbo_frame_tag "tags_list", class: "flex flex-wrap gap-2" do %>
    <% unless @tags.blank? %>
      <% @tags.each do |tag| %>
        <li><%= render tag %></li>
      <% end %>
    <% else %>
      <li>You haven't added any tags yet!</li>
    <% end %>
  <% end %>
</ul>