config/routes.rb
Rails.application.routes.draw do
  # Authentication routes
  devise_for :users

  # Application routes
  resources :houses, only: [:index, :create, :edit, :update, :destroy] do
    resources :invites, only: [:create]
  end
  resources :rooms, only: [:create, :edit, :update, :destroy]
  resources :boxes, only: [:show, :create, :destroy]
  resources :items do
    resources :tags, only: [] do
      delete :remove, on: :member
    end
  end
  resources :tags, only: [:index, :edit, :create, :update, :destroy]
  resources :invites, only: [:update]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "items#index"
end

app/models/room.rb
# frozen_string_literal: true

# Represents a room or area where items can be stored
class Room < ApplicationRecord
  belongs_to :house, counter_cache: true
  has_many :boxes, dependent: :restrict_with_error
  has_many :unboxed_items, class_name: 'Item', dependent: :restrict_with_error
  has_many :boxed_items, through: :boxes, source: :items

  validates :name, presence: true

  scope :in_house, ->(house) { where(house_id: house) }

  def items
    Item.where(id: (unboxed_items.ids + boxed_items.ids))
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ edit update destroy ]

  def create
    @room = Room.new(room_params)
    authorize @room
    @house = @room.house

    if @room.save
      respond_to do |format|
        format.html { redirect_to houses_path, notice: "Room was successfully created." }
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(
            dom_id(@house),
            partial: "houses/house",
            locals: { house: @house, new_room: Room.new, new_invite: Invite.new }
          )
        end
      end
    else
      @houses = House.includes(:rooms).all
      respond_to do |format|
        format.html { render "houses/index", status: :unprocessable_entity }
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(
            dom_id(@house),
            partial: "houses/house",
            locals: { house: @house, new_room: @room, new_invite: Invite.new }
          )
        end
      end
    end
  end

  def edit
    authorize @room
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(
          dom_id(@room),
          partial: "rooms/form",
          locals: { house: @room.house, room: @room }
        )
      end
    end
  end

  def update
    authorize @room
    @house = @room.house

    if @room.update(room_params)
      respond_to do |format|
        format.html { redirect_to houses_path, notice: "Room was successfully updated.", status: :see_other }
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(
            dom_id(@house),
            partial: "houses/house",
            locals: { house: @house, new_room: Room.new, new_invite: Invite.new }
          )
        end
      end
    else
      @houses = House.includes(:rooms).all
      respond_to do |format|
        format.html { render "houses/index", status: :unprocessable_entity }
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(
            dom_id(@house),
            partial: "houses/house",
            locals: { house: @house, new_room: @room, new_invite: Invite.new }
          )
        end
      end
    end
  end

  def destroy
    authorize @room
    frame_id = dom_id(@room)
    @room.destroy!
    respond_to do |format|
      format.html { redirect_to "houses/index", notice: "Room was successfully destroyed.", status: :see_other }
      format.turbo_stream do
        render turbo_stream: turbo_stream.remove(frame_id)
      end
    end
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:name, :house_id)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= turbo_frame_tag dom_id(room) do %>
  <%= simple_form_for(room, html: { data: { turbo_frame: "room_#{room.id}" }, class: "p-2 rounded-xl bg-slate-100 dark:bg-slate-900 shadow-sm dark:shadow-sm/70 border-1 border-slate-200 dark:border-slate-800"  }) do |f| %>
    <%= f.hidden_field :house_id, value: house.id %>

    <% if room.errors.any? %>
      <%= render "shared/form_errors", resource: room%>
    <% end %>

    <div class="flex gap-2">
      <%= f.input :name,
        label: "Room name",
        label_html: { class: "sr-only" },
        placeholder: "Room name",
        wrapper_html: { class: "grow" },
        error_html: { class: "text-red-400 text-sm mt-1" },
        input_html: {
          class: "grow w-full rounded-md border-1 border-slate-300 dark:border-slate-700  bg-slate-300 dark:bg-slate-800 text-lg text-slate-950 dark:text-slate-100 placeholder:text-slate-500 placeholder:dark:text-slate-500 p-2 focus:outline-none focus:ring-2 focus:ring-teal-400"
        }
      %>

      <% if room.id == nil %>
        <%= f.button :submit, "Add room", class: "cursor-pointer bg-teal-500 hover:bg-teal-600 text-slate-100 px-4 py-2 rounded shadow-sm focus:outline-none focus:ring-2 focus:ring-teal-400" %>
      <% else %>
        <%= f.button :submit, "Save", class: "cursor-pointer bg-teal-500 hover:bg-teal-600 text-slate-100 px-4 py-2 rounded shadow-sm focus:outline-none focus:ring-2 focus:ring-teal-400" %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/rooms/_house_rooms.html.erb
<details class="py-2 group">
  <summary class="cursor-pointer flex justify-between items-center text-xl text-slate-600 dark:text-slate-400">
    <div class="flex gap-2 items-center">
      <%= render "shared/icons/room", klasses: "ml-2 w-6 h-6"  %>
      <%= house.rooms_count %> room<%= 's' if house.rooms_count != 1 %>
    </div>
    <%= render "shared/icons/chevron_left", klasses: "group-open:-rotate-90 transition-all ease-linear duration-150"  %>
  </summary>
  <div class="mt-2 flex flex-col gap-2 mb-6 p-2 bg-slate-300 dark:bg-slate-700 rounded-xl">
    <% house.rooms.each do |room| %>
      <%= render "rooms/room", room: room %>
    <% end %>

    <% form_room = new_room&.house_id == house.id ? new_room : Room.new(house: house) %>
    <%= render "rooms/form", house: house, room: form_room %>
  </div>
</details>

app/views/rooms/_room.html.erb
<%= turbo_frame_tag dom_id(room) do %>
  <div class="shadow-sm dark:shadow-sm/70 p-2 flex justify-between items-center border-1 border-slate-200 dark:border-slate-800 bg-slate-100 dark:bg-slate-900 rounded-xl">
    <div>
      <p class="ml-2 text-slate-900 dark:text-slate-100">
        <%= room.name.capitalize %>
      </p>
      <div class="flex gap-2">
        <%= render "shared/badge", icon: "box" do %>
          <%= room.boxes_count %> box<%= 'es' if room.boxes_count != 1 %>
        <% end %>
        <%= render "shared/badge", icon: "items" do %>
          <%= room.items.count %> item<%= 's' if room.items.count != 1 %>
        <% end %>
      </div>
    </div>
    <div class="flex gap-2">
      <%= link_to edit_room_path(room, format: :turbo_stream), data: { turbo_prefetch: false } do %>
        <%= render "shared/icons/pencil", klasses: "stroke-teal-500 dark:stroke-teal-500 hover:stroke-teal-400" %>
      <% end %>
      <% if room.items.count == 0 %>
        <%= link_to room_path(room), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
          <%= render "shared/icons/trash", klasses: "stroke-teal-500 dark:stroke-teal-500 hover:stroke-teal-400" %>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>