config/routes.rb
Rails.application.routes.draw do
  # Authentication routes
  devise_for :users

  # Application routes
  resources :houses, only: [:index, :create, :edit, :update, :destroy] do
    resources :invites, only: [:create]
  end
  resources :rooms, only: [:create, :edit, :update, :destroy]
  resources :boxes, only: [:show, :create, :destroy]
  resources :items do
    resources :tags, only: [] do
      delete :remove, on: :member
    end
  end
  resources :tags, only: [:index, :edit, :create, :update, :destroy]
  resources :invites, only: [:update]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "items#index"
end

app/models/item.rb
# frozen_string_literal: true

# An item in a users' house
class Item < ApplicationRecord
  include Searchable

  belongs_to :user
  belongs_to :house, counter_cache: true
  belongs_to :room
  belongs_to :box, optional: true

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  has_one_attached :image
  attr_accessor :remove_image

  after_save :purge_image, if: -> { remove_image == '1' }

  validates :name, presence: true
  validates :notes, length: { maximum: 255 }, allow_blank: true
  validate :in_same_house_as_box, if: -> { box.present? }
  validate :in_same_house_as_room

  private

  def in_same_house_as_box
    return if box.house == house

    errors.add(:box, 'must be in the same house as the item')
  end

  def in_same_house_as_room
    return if room&.house == house

    errors.add(:room, 'must be in the same house as the item')
  end

  def purge_image
    image.purge
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

# Items controller
class ItemsController < ApplicationController
  before_action :set_items, only: %i[index]
  before_action :set_tags, only: %i[index]
  before_action :set_boxes, only: %i[index]
  before_action :set_rooms, only: %i[index]
  before_action :set_houses, only: %i[index]
  before_action :set_partial, only: [:show]

  before_action :set_item, only: %i[show edit update destroy]

  def index
    @pagy, @items = pagy(@items)
  end

  def show
    respond_to do |format|
      format.html { render :index }
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(
          dom_id(@item),
          partial: @partial,
          locals: { item: @item }
        )
      end
    end
  end

  def new
    @item = Item.new
    authorize @item

    @boxes = policy_scope(Box).includes(room: :house).order(:house_id).order(:number)
    @rooms = policy_scope(Room).includes(:house).order(:house_id, :name)

    @tag = Tag.new
    @box = Box.new
  end

  def edit
    @boxes = policy_scope(Box).includes(room: :house).order(:house_id).order(:number)
    @rooms = policy_scope(Room).includes(:house).order(:house_id, :name)

    respond_to do |format|
      format.html
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(
          dom_id(@item),
          partial: 'items/edit',
          locals: { item: @item, boxes: @boxes, rooms: @rooms }
        )
      end
    end
  end

  def create
    @item = Item.new(item_params)
    @item.house = @item.room&.house
    @item.user = current_user
    authorize @item

    if @item.save
      respond_to do |format|
        format.html { redirect_to items_path, notice: 'Item was successfully created.' }
        # format.turbo_stream do
        #   render turbo_stream: turbo_stream.append(
        #     "items_list",
        #     partial: "items/item",
        #     locals: { item: @item }
        #   )
        # end
      end
    else
      @boxes = policy_scope(Box).includes(room: :house).order(:house_id).order(:number)
      @rooms = policy_scope(Room).includes(:house).order(:house_id, :name)

      @tag = Tag.new
      @box = Box.new

      render :new, status: :unprocessable_content
    end
  end

  def update
    params.delete(:box_id) if params[:room_id] && @item.room.nil?
    params.delete(:room_id) if params[:box_id] && @item.box.nil?

    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.', status: :see_other }
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(
            dom_id(@item),
            partial: 'items/item',
            locals: { item: @item }
          )
        end
      else
        format.html { render :edit, status: :unprocessable_content }
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(
            dom_id(@item),
            partial: 'items/edit',
            locals: { item: @item }
          )
        end
      end
    end
  end

  def destroy
    frame_id = dom_id(@item)
    @item.destroy!

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove(frame_id) }
    end
  end

  private

  def set_item
    @item = Item.find(params[:id])
    authorize @item
  end

  def set_items
    all_items = policy_scope(Item)&.includes(:room, :box, image_attachment: :blob)
    @items = params[:search].present? ? all_items.search(params[:search]) : all_items
    @number_of_items = @items.count
  end

  def set_tags
    @tags = policy_scope(Tag)
  end

  def set_boxes
    @boxes = policy_scope(Box)
  end

  def set_rooms
    @rooms = policy_scope(Room).includes(:house)
  end

  def set_houses
    @houses = policy_scope(House)
  end

  def set_partial
    @partial = params[:closed] == 'true' ? 'items/item' : 'items/item_open'
  end

  def item_params
    params.expect(item: [:name, :notes, :box_id, :room_id, :image, :remove_image, { tag_ids: [] }])
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_edit.html.erb
<%= turbo_frame_tag dom_id(item) do %>
  <div class="bg-slate-50 dark:bg-slate-900 rounded-xl shadow-md dark:shadow-md/90 p-4">
    <%= render "items/form", item: item, boxes: @boxes, rooms: @rooms %>
  </div>
<% end %>

app/views/items/_form.html.erb
<%= simple_form_for(@item, html: { class: "" }) do |f| %>
  <div class="flex justify-between mb-4">
    <% if controller.action_name == "edit" %>
      <h3 class="font-semibold text-xl text-slate-900 dark:text-slate-200">
        Edit item
      </h3>
      <%= link_to items_path, class: "max-w-min focus:outline-none focus:ring-2 focus:ring-teal-400" do %>
        <%= render "shared/icons/close", klasses: "w-6 h-6 stroke-teal-500 dark:stroke-teal-500 hover:stroke-teal-400" %>
      <% end %>
    <% end %>
  </div>

  <% if @item.errors.any? %>
    <%= render "shared/form_errors", resource: @item %>
  <% end %>

  <div data-controller="item-location" class='flex flex-col gap-2'>
    <%= f.input :name,
      required: false,
      label: "Name:",
      label_html: { class: "font-bold text-slate-950 dark:text-slate-100" },
      placeholder: "Item name",
      error_html: { class: "text-red-400 text-sm mt-1" },
      input_html: {
        class: "mt-2 w-full rounded-md bg-slate-200 dark:bg-slate-800 text-lg text-slate-950 dark:text-slate-100 placeholder:text-slate-500 placeholder:dark:text-slate-500 p-2 focus:outline-none focus:ring-2 focus:ring-teal-400"
      }
    %>


      <%= simple_fields_for :option do |o| %>
        <%= o.input :options, collection: [[true, 'Yes'], [false, 'No']], as: :radio_buttons,
          checked: @item.room.blank?,
          wrapper_html: { class: "py-2 flex gap-2 min-w-max items-center"},
          value_method: :first,
          label_method: :last,
          label: "In a box?",
          required: false,
          label_html: { class: "font-bold text-slate-950 dark:text-slate-100" },
          input_html: {
            data: { action: "change->item-location#toggle", item_location_target: "radioButton" },
            class: "text-slate-950 dark:text-slate-100 me-1 cursor-pointer"
          },
          item_wrapper_class: "text-slate-950 dark:text-slate-100"
        %>
      <% end %>

    <div data-item-location-target="boxSelectWrapper" class="<%= @item.room.blank? ? "text-slate-900 dark:text-slate-100" : "hidden" %> grow transition-all ease-in-out duration-300">
      <%= f.input :box_id, as: :select,
        wrapper: :inline_label,
        collection: boxes.map { |box| ["#{box.number} - #{box.house.name.capitalize}", box.id] },
        include_blank: "-",
        label: "Box:",
        label_html: { class: "font-bold text-slate-950 dark:text-slate-100" },
        error_html: { class: "text-red-400 text-sm mt-1" },
        input_html: {
          data: { item_location_target: "boxSelectInput" },
          class: "#{@item.room.blank? ? "" : "hidden"} w-full text-slate-900 dark:text-slate-100 bg-slate-200 dark:bg-slate-800 border-1 border-slate-200 dark:border-slate-800 cursor-pointer w-full rounded-md p-2 focus:outline-none focus:ring-2 focus:ring-teal-400"
        }
      %>
    </div>

    <div data-item-location-target="roomSelectWrapper" class="<%= @item.room.present? ? "text-slate-900 dark:text-slate-100" : "hidden" %> grow transition-all ease-in-out duration-300">
      <%= f.input :room_id, as: :select,
        wrapper: :inline_label,
        collection: rooms.map { |room| ["#{room.name.capitalize} - #{room.house.name.capitalize}", room.id] },
        include_blank: "-",
        label: "Room:",
        label_html: { class: "font-bold text-slate-950 dark:text-slate-100" },
        error_html: { class: "text-red-400 text-sm mt-1" },
        input_html: {
          data: { item_location_target: "roomSelectInput" },
          class: "#{@item.room.present? ? "" : "hidden"} w-full text-slate-900 dark:text-slate-100 bg-slate-200 dark:bg-slate-800 border-1 border-slate-200 dark:border-slate-800 cursor-pointer w-full rounded-md p-2 focus:outline-none focus:ring-2 focus:ring-teal-400"
        }
      %>
    </div>

    <%= f.input :notes,
      as: :text,
      label: "Notes:",
      label_html: { class: "font-bold text-slate-950 dark:text-slate-100" },
      error_html: { class: "text-red-400 text-sm mt-1" },
      input_html: {
        rows: 4,
        class: "mt-2 w-full rounded-md bg-slate-200 dark:bg-slate-800 text-slate-950 dark:text-slate-100 p-2 focus:outline-none focus:ring-2 focus:ring-teal-400"
      }
    %>

    <%= f.association :tags,
      label: "Tags:",
      label_html: { class: "font-bold text-slate-950 dark:text-slate-100 mb-1" },
      error_html: { class: "text-red-400 text-sm mt-1" },
      input_html: {
        rows: 4,
        class: "mt-2 w-full rounded-md bg-slate-200 dark:bg-slate-800 text-slate-950 dark:text-slate-100 p-2 focus:outline-none focus:ring-2 focus:ring-teal-400 cursor-pointer"
      }
    %>

    <% if f.object.image.attached? %>
      <div class="flex gap-2 items-center">

        <div class="text-slate-900 dark:text-slate-100">
          <% if f.object.image.variable? %>
            <%= image_tag f.object.image.variant(resize_to_limit: [100, 100]), class: "mt-1 rounded-xl w-[100px] h-[100px] min-w-[100px] max-h-[100px]" %>
          <% else %>
            <%= link_to f.object.image.filename.to_s, url_for(f.object.image), class: "underline text-teal-600 hover:text-teal-700" %>
          <% end %>
        </div>

        <div class="self-center">
          <%= f.check_box :remove_image %>
          <%= f.label :remove_image, "Remove image", class: "ml-2 text-red-600 dark:text-red-400" %>

          <%= f.input :image,
            as: :file,
            label: "Replace image:",
            label_html: { class: "font-bold text-slate-950 dark:text-slate-100 mb-1" },
            placeholder_html: { class: "ml-4" },
            error_html: { class: "text-red-400 text-sm mt-1" },
            input_html: {
              direct_upload: true,
              class: "mt-2 border-0 w-full bg-slate-200 file:text-slate-100 file:bg-teal-500 hover:file:bg-teal-600 dark:file:bg-teal-600 file:px-4 file:py-2 file:rounded file:cursor-pointer hover:file:cursor-pointer hover:cursor-pointer dark:bg-slate-800 dark:text-slate-200 rounded-md focus:outline-none focus:ring-2 focus:ring-teal-400"
            }
          %>
        </div>
      </div>
    <% else %>
      <%= f.input :image,
        as: :file,
        label: "Add image:",
        label_html: { class: "font-bold text-slate-950 dark:text-slate-100 mb-1" },
        placeholder_html: { class: "ml-4" },
        error_html: { class: "text-red-400 text-sm mt-1" },
        input_html: {
          direct_upload: true,
          class: "mt-2 border-0 w-full bg-slate-200 file:text-slate-100 file:bg-teal-500 hover:file:bg-teal-600 dark:file:bg-teal-600 file:px-4 file:py-2 file:rounded file:cursor-pointer hover:file:cursor-pointer hover:cursor-pointer dark:bg-slate-800 dark:text-slate-200 rounded-md focus:outline-none focus:ring-2 focus:ring-teal-400"
        }
      %>
    <% end %>
    <div class="mt-6 flex <%= @item.id.present? ? "justify-between" : "justify-end" %>">
      <% if @item.id.present? %>
        <%= link_to item_path(@item), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete #{@item.name}?" }, class: "text-teal-500 group hover:text-teal-400 flex gap-1 items-center focus:outline-none focus:ring-2 focus:ring-teal-400" do %>
          <%= render "shared/icons/trash", klasses: "stroke-teal-500 dark:stroke-teal-500 group-hover:stroke-teal-400" %>
          Delete item
        <% end %>
      <% end %>

      <div class="flex gap-2">
        <%= link_to "Cancel", items_path, class: "max-w-max cursor-pointer bg-slate-500 hover:bg-slate-600 text-slate-100 px-4 py-2 rounded shadow-sm focus:outline-none focus:ring-2 focus:ring-teal-400" %>
        <%= f.button :submit, "Save", class: "max-w-max cursor-pointer bg-teal-500 hover:bg-teal-600 text-slate-100 px-4 py-2 rounded shadow-sm focus:outline-none focus:ring-2 focus:ring-teal-400" %>
      </div>
    </div>
  </div>
<% end %>

app/views/items/_item.html.erb
<%= turbo_frame_tag dom_id(item) do %>
  <li>
    <%= link_to item_path(item, format: :turbo_stream), data: { turbo_frame: dom_id(item), turbo_prefetch: false }, class: "bg-slate-50 dark:bg-slate-900 rounded-xl shadow-md dark:shadow-md/90 p-4 flex gap-2 items-center justify-between hover:shadow-lg dark:hover:shadow-lg/90 hover:-translate-y-1 transition ease-linear duration-150 active:translate-0 active:shadow-sm dark:active:shadow-sm/90 focus:outline-none focus:-translate-y-1" do %>
      <div class="flex flex-col gap-2 ">
        <h3 class="text-md lg:text-xl font-semibold col-span-2 text-slate-900 dark:text-slate-100">
          <%= item.name.capitalize %>
        </h3>

        <div class="flex items-center flex-wrap gap-1 text-sm lg:text-lg text-slate-500 stroke-slate-500 dark:text-slate-400 dark:stroke-slate-400">
          <div class="flex gap-1 items-center flex-wrap">
            <%= render "shared/icons/map_pin", klasses: "w-4 h-4" %>
            <%= item.box&.room&.house&.name || item&.room&.house&.name %>
          </div>

          <div class="flex gap-1 items-center flex-wrap">
            <%= render "shared/icons/arrow_long_right", klasses: "w-4 h-4" %>
            <%= item.box&.room&.name&.capitalize || item&.room&.name&.capitalize %>
          </div>

          <% if item.box.present? %>
            <div class="flex gap-1 items-center flex-wrap">
              <%= render "shared/icons/arrow_long_right", klasses: "w-4 h-4" %>
              Box <%= item.box.number %>
            </div>
          <% end %>
        </div>
      </div>

      <% if item.image.attached? && item.image.variable? %>
          <%= image_tag item.image.variant(resize_to_limit: [100, 100]), alt: "Picture of #{item.name}", class: "w-[70px] h-[70px] object-cover rounded-xl text-slate-950 dark:text-slate-100" %>
      <% end %>
    <% end %>
  </li>
<% end %>

app/views/items/_item_open.erb
<%= turbo_frame_tag dom_id(item) do %>
  <li
    class="relative flex flex-col gap-4 bg-slate-50 dark:bg-slate-900 border-teal-500 p-4 rounded-xl shadow-md dark:shadow-md/90 cursor-pointer hover:shadow-lg dark:hover:shadow-lg/90 hover:-translate-y-1 transition ease-linear duration-150 active:translate-0 active:shadow-sm dark:active:shadow-sm/90 focus:outline-none"
    data-controller="turbo-navigator"
    data-turbo-navigator-url-value="<%= item_path(item, closed: true, format: :turbo_stream) %>"
    data-turbo-navigator-frame-value="<%= dom_id(item) %>"
    data-action="click->turbo-navigator#visit"
    role="link" tabindex="0"
  >
    <div class="flex flex-col gap-2">
      <div class="flex justify-between">
        <h3 class="font-semibold text-xl text-slate-900 dark:text-slate-200">
          <%= @item.name.capitalize %>
        </h3>

        <%= link_to edit_item_path(@item, format: :turbo_stream), data: { turbo_frame: dom_id(item), turbo_prefetch: false }, class: "focus:outline-none focus:ring-2 focus:ring-teal-400" do %>
          <%= render "shared/icons/pencil", klasses: "stroke-teal-500 dark:stroke-teal-500 hover:stroke-teal-400" %>
        <% end %>

      </div>

      <div class="text-md flex gap-1 text-sm lg:text-lg text-slate-500 stroke-slate-500 dark:text-slate-400 dark:stroke-slate-400">
        <div class="flex gap-1 items-center flex-wrap">
          <%= render "shared/icons/map_pin", klasses: "w-4 h-4" %>
          <%= @item.box&.room&.house&.name || @item&.room&.house&.name %>
        </div>

        <div class="flex gap-1 items-center flex-wrap">
          <%= render "shared/icons/arrow_long_right", klasses: "w-4 h-4" %>
          <%= @item.box&.room&.name&.capitalize || @item&.room&.name&.capitalize %>
        </div>

        <% if @item.box.present? %>
          <div class="flex gap-1 items-center flex-wrap">
            <%= render "shared/icons/arrow_long_right", klasses: "w-4 h-4" %>
            Box <%= @item.box.number %>
          </div>
        <% end %>
      </div>

      <% if @item.notes %>
        <p class=" text-slate-950 dark:text-slate-200">
          <%= @item.notes %>
        </p>
      <% end %>
    </div>

    <% if @item.tags.present? %>
      <div class="flex flex-wrap gap-2">
        <% @item.tags.each do |tag|  %>
          <%= render "tags/tag", tag: tag, item: @item %>
        <% end %>
      </div>
    <% end %>

    <% if @item.image.attached? %>
        <%= image_tag @item.image, alt: "Picture of #{item.name}", class: "rounded-xl mt-2 text-slate-400 dark:text-slate-400", style: "height: 300px; object-fit: cover; object-position: center" %>
    <% end %>
  </li>
<% end %>

app/views/items/index.html.erb
<div class="md:flex max-w-screen justify-content-center">
  <section class="mt-4 mx-2 md:mx-6 md:max-w-sm">
    <%= render "search" %>
  </section>

  <section class="md:mx-6 w-full max-h-[90vh] overflow-scroll">
    <div class="flex justify-between content-center pt-4 px-6">
      <h1 class="text-4xl font-bold">Items</h1>

      <%= link_to "Add item +", new_item_path, class: "block py-2 px-6 bg-teal-500 hover:bg-teal-600 text-slate-100 dark:text-slate-900 rounded shadow-sm dark:shadow-sm/90 focus:outline-none focus:ring-2 focus:ring-teal-400" %>
    </div>

    <%= turbo_frame_tag :items do %>
      <p class="text-center mt-4 mb-2 max-h-min font-medium text-md md:text-lg text-slate-600 dark:text-slate-400">
        <%= @number_of_items %> results
      </p>

      <ul class="mb-4 p-2">
        <%= turbo_frame_tag :items_list, class: "flex flex-col gap-4" do %>
          <% @items.each do |item| %>
            <%= render partial: "item", locals: { item: item } %>
          <% end %>
        <% end %>
        <% if @items.blank? %>
          <li class="mb-8 pl-6 text-md md:text-lg text-slate-950 dark:text-slate-200">
              No items found.
          </li>
        <% end %>
      </ul>

      <div class="mb-8 flex items-center justify-center">
        <%== pagy_nav(@pagy) %>
      </div>
    <% end %>
  </section>
</div>

app/views/items/new.html.erb
<h1 class="mt-8 mx-6 text-4xl font-bold">Add Item</h1>

<div class="mx-2 my-6 p-4 pb-4 bg-slate-50 dark:bg-slate-900 rounded-xl shadow-md dark:shadow-md/90">
  <%= render "items/form", item: @item, boxes: @boxes, rooms: @rooms %>
</div>


<h2 class="mt-8 px-6 text-2xl font-bold">Add Box</h2>
<div class="m-2">
  <%= render "boxes/form", box: @box, houses: @houses, rooms: @rooms %>
</div>

<h2 class="mt-8 px-6 text-2xl font-bold">Add Tag</h2>
<div class="m-2 mb-8">
  <%= render "tags/form", tag: @tag %>
</div>

app/views/items/show.html.erb
<div class="m-2 relative flex flex-col gap-4 items-centerr bg-slate-50 dark:bg-slate-900 p-4 shadow-md dark:shadow-md/90">
  <div class="flex flex-col gap-2">
    <h3 class="mb-2 font-semibold text-xl md:text-2xl col-span-2 text-slate-900 dark:text-slate-100">
      <%= @item.name.capitalize %>
    </h3>

    <div class="text-lg flex gap-4 text-slate-200 stroke-slate-500 dark:text-slate-400 dark:stroke-slate-400">
      <div class="flex gap-2 items-centerr flex-wrap">
        <%= render "shared/icons/room" %>
        <%= @item.box&.room&.name&.capitalize || @item.room.name.capitalize %>
      </div>
      <% if @item.box.present? %>
        <div class="flex gap-2 items-centerr flex-wrap">
          <%= render "shared/icons/box" %>
          Box <%= @item.box.number %>
        </div>
      <% end %>
    </div>

    <div class="flex gap-2 items-centerr flex-wrap text-lg text-slate-200 stroke-slate-500 dark:text-slate-400 dark:stroke-slate-400">
      <%= render "shared/icons/house" %>
      <%= @item.box&.room&.house&.name || @item.room.house.name %>
    </div>

    <% if @item.notes %>
      <p class=" text-slate-950 dark:text-slate-200">
        <%= @item.notes %>
      </p>
    <% end %>
  </div>

  <% if @item.tags.present? %>
    <div class="flex flex-wrap gap-2">
      <% @item.tags.each do |tag|  %>
        <%= render "tags/tag", tag: tag, item: @item %>
      <% end %>
    </div>
  <% end %>

  <img src="https://loremflickr.com/500/500/<%= @item.name.gsub(" ", "-") %>" alt="Picture of <%= @item.name %>" width="500" height="500" class="mt-2 block self-center rounded-xl">
  <%# if @post.image.attached? %>
      <%#= image_tag @post.image.variant(resize_to_limit: [500, 500]), alt: "Picture of #{item.name}", class: "rounded-xl max-w-24" %>
  <%# end %>

  <div class="flex justify-between text-sm">
    <%= link_to item_path(@item), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "inline-flex gap-2 items-centerr justify-center text-slate-950 dark:text-slate-200 stroke-slate-950 dark:stroke-slate-950" do %>
      <%= render "shared/icons/trash", klasses: "w-5 h-5" %>
      Delete
    <% end %>
    <%= link_to edit_item_path(@item), class: "inline-flex gap-2 items-centerr justify-center text-slate-950 dark:text-slate-200 stroke-slate-950 dark:stroke-slate-50" do %>
      <%= render "shared/icons/pencil", klasses: "w-5 h-5" %>
      Edit
    <% end %>
  </div>
</div>